# spring??
spring:
  application:
    name: hjy-community-module
  profiles:
    active: druid

# ??????
hjy-community:
  name: hjy-community
  version: 1.0.0 # ??

#??????
server:
  port: 8888
  servlet:
    context-path: / # ???????
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30 # tomcat?????????
      max: 800 # tomcat?????

# ????
logging:
  level:
    org.springframework: warn
    com.personal: debug

# PageHelper????
pagehelper:
#  dialect: mysql # ?????
  # ???????true???pageNum<=0?????????pageNum>pages???????????????
  reasonable: true
  # ?????????????PageNum?PageSize?????????
  support-methods-arguments: true
  # ????pageStart?????????????????????????????
  params: count=countSql

# mybatis-plus??
mybatis-plus:
  # ????XXXmapper.xml????????????????????????
  type-aliases-package: com.personal.hjycommunity.**.domain
  mapper-locations: classpath*:/mapper/**/*.xml
  # mybatis-config ??????
  config-location: classpath:mybatis/mybatis-config.xml
  # ????
  global-config:
    db-config:
      # id???????id
      id-type: assign_id
    banner: false # ??mybatis-plus ?banner