# spring??
spring:
  application:
    name: hjy-community-module
  profiles:
    active: druid
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf:
#    prefix: classpath:/templates/ # 默认就是classpath:/templates/
#    suffix: .html # 默认就是.html
#    encoding: utf-8 #默认值
#    mode: HTML #默认值
    cache: false
#  配置的目的:方便测试
  security:
    user:
      name: test
      password: 123456
      roles: 普通用户,超级管理员


# ??????
hjy-community:
  name: hjy-community
  version: 1.0.0 # ??

#??????
server:
  port: 8888
  servlet:
    context-path: /hejiayun # ???????
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30 # tomcat?????????
      max: 800 # tomcat?????

# ????
logging:
  level:
    org.springframework: warn
    com.personal: debug

# PageHelper????
pagehelper:
#  dialect: mysql # ?????
  # ???????true???pageNum<=0?????????pageNum>pages???????????????
  reasonable: true
  # ?????????????PageNum?PageSize?????????
  support-methods-arguments: true
  # ????pageStart?????????????????????????????
  params: count=countSql

# mybatis-plus??
mybatis-plus:
  # ????XXXmapper.xml????????????????????????
  type-aliases-package: com.personal.hjycommunitymodule.**.domain
  mapper-locations: classpath*:/mapper/**/*.xml
  # mybatis-config ??????
  config-location: classpath:mybatis/mybatis-config.xml
  # ????
  global-config:
    db-config:
      # id???????id
      id-type: assign_id
    banner: false # ??mybatis-plus ?banner

